@isTest (SeeAllData=true) 
private class TestManaged_ClauseStepTrigger { 
    private static testMethod void Test_Managed_ClauseStepTrigger () { 
       /* try{
            FSTR__Business_Process__c fw = new FSTR__Business_Process__c(); 
            insert fw; 
            APXT_Redlining__Managed_Clause__c cso = new APXT_Redlining__Managed_Clause__c(); 
            insert cso; 
            update cso; 
            delete cso;  
        }catch(Exception e){
            FSTR.COTestFactory.FillAllFields=true;
            FSTR__Business_Process__c fw = new FSTR__Business_Process__c(); 
            insert fw; 
            APXT_Redlining__Managed_Clause__c cso = (APXT_Redlining__Managed_Clause__c)FSTR.COTestFactory.createSObject('APXT_Redlining__Managed_Clause__c',true);
            insert cso; 
            update cso; 
            delete cso;  
        }
*/
    } 
}