@isTest (SeeAllData=true)
private class TestManaged_ClauseBothTrigger { 
    private static testMethod void Test_Managed_ClauseBothTrigger () { 
       /* try{
            APXT_Redlining__Managed_Clause__c fw = new APXT_Redlining__Managed_Clause__c(); 
            insert fw; 
            System.assertNotEquals(null, fw.id); 
            update fw; 
            delete fw;
        } catch(Exception e){
            FSTR.COTestFactory.FillAllFields=true;
            APXT_Redlining__Managed_Clause__c fw = (APXT_Redlining__Managed_Clause__c)FSTR.COTestFactory.createSObject('APXT_Redlining__Managed_Clause__c',true); 
            insert fw; 
            System.assertNotEquals(null, fw.id); 
            update fw; 
            delete fw;
        }
*/
    } 
}